data:
  dataset: {name: titanic, samples: 1316, type: public}
  datasetLoadOption: batch
  kfold: 1
  mapping:
    age:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    class:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    sex:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    survived:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples: {split: 3, test: 131, training: 1052, validation: 131}
  shuffle: false
model:
  connections:
  - {source: Dense_1, target: Dropout_1}
  - {source: Dropout_1, target: Dense_2}
  - {source: Dense_2, target: Output_1}
  - {source: Input_1, target: Dense_1}
  layers:
  - args: {activation: relu, output_dim: '100'}
    class: Dense
    name: Dense_1
    x: 257
    y: 211
  - args: {activation: softmax, output_dim: '2'}
    class: Dense
    name: Dense_2
    x: 255
    y: 498
  - args: {p: '0.2'}
    class: Dropout
    name: Dropout_1
    x: 268
    y: 333
  - args: {}
    class: Input
    name: Input_1
    x: 273
    y: 60
  - args: {}
    class: Output
    name: Output_1
    x: 255
    y: 633
params:
  batch_size: '32'
  loss_func: categorical_crossentropy
  num_epoch: '20'
  optimizer: {name: Adadelta}
project: Titanic Survival Prediction